<?php
//Generate configuration file
//Delete/move this after config file creation!
error_reporting(E_ALL);
//$initjsondata = "//STFSumar Configuration File\r\n";
//$initjsondata .= "//P7COMunications LTD S.A - PANCHO7532\r\n";
//$initjsondata .= "//Generated by 'generate.php' at: " . date("F j, Y, h:i:s a P"). "\r\n";

$jsonarray = array(
	"dbhost" => "intercom.sumar5.net",
	"dbuser" => "usuario5",
	"dbpass" => "sumar",
	"dbport" => "3306",
	"dbname" => "sumar",
	"usemysqli" => "inactive",
);
$jsonstage = json_encode($jsonarray);
$jsonfile = "./config.inc.js";
unlink($jsonfile);
$jsonstage2 = fopen($jsonfile, "a");
fwrite($jsonstage2, $jsonstage);
fclose($jsonstage2);
echo "<head><title>Restauracion config.inc.js</title></head><fieldset><legend>Operacion Exitosa</legend><p>El archivo de configuracion ha sido devuelto a sus valores de fabrica, por favor reconfigure los parametros necesarios en caso que se lo requiera.</p></fieldset>";
?>